// Capital Cities of the World

const capitalCities = [
    {   continent: 'North America',
        country: 'United States',
        city: 'Irvine',
        latitude: 33.669444, 
        longitude: -117.823056,
    },
    {   continent: 'Europe',
        country: 'France',
        city: 'Paris',
        latitude: 48.8567,
        longitude: 2.3508,
    },
    {   continent:'Africa',
        country: 'Morocco',
        city: 'Rabat',
        latitude: 34.020882, 
        longitude: -6.84165,
    },
    {   continent: 'Asia',
        country: 'Cambodia',
        city: 'Phnom Penh',
        latitude: 11.55, 
        longitude: 104.916667,
    },
    {   continent: 'Europe',
        country: 'Turkey',
        city: 'Ankara',
        latitude: 39.933333,  
        longitude: 32.866667,
    },
    {   continent: 'Asia',
        country: 'Vietnam',
        city: 'Hanoi',
        latitude: 21.028333, 
        longitude: 105.854167,
    },
    {   continent: 'Europe',
        country: 'Czech Republic',
        city: 'Prague',
        latitude: 50.083333, 
        longitude: 14.416667,
    },
    {   continent: 'Europe',
        country: 'London',
        city: 'United Kingdom',
        latitude: 51.507222, 
        longitude: -0.1275,
    },
    {   continent: 'Europe',
        country: 'Italy',
        city: 'Rome',
        latitude: 41.9, 
        longitude: 12.5,
    },
    {   continent: 'South America',
        country: 'Argentina',
        city: 'Buenos Aires',
        latitude: -34.603333, 
        longitude: -58.381667,
    },
    {   continent: 'Africa',
        country: 'South Africa',
        city: 'Cape Town',
        latitude: -33.925278, 
        longitude: 18.423889,
    },
    {   continent: 'Europe',
        country: 'Spain',
        city: 'Madrid',
        latitude: 40.383333, 
        longitude: -3.716667,
    },
    {   continent: 'Asia',
        country: 'Indonesia',
        city: 'Jakarta',
        latitude: -6.2, 
        longitude: 106.816667,
    },
    {   continent: 'South America',
        country: 'Peru',
        city: 'Lima',
        latitude: -12.043333, 
        longitude: -77.028333,
    },
    {   continent: 'Europe',
        country: 'Russia',
        city: 'Moscow',
        latitude: 55.75, 
        longitude: 37.616667,
    },
    {   continent: 'Asia',
        country: 'Nepal',
        city: 'Kathmandu',
        latitude: 27.711389, 
        longitude: 85.308611,
    },
    {   continent: 'Europe',
        country: 'Greece',
        city: 'Athens',
        latitude: 37.983972, 
        longitude: 23.727806,
    },
    {   continent: 'Asia',
        country: 'South Korea',
        city: 'Seoul',
        latitude: 37.566667,  
        longitude: 126.966667,
    },
    {   continent: 'Asia',
        country: 'China',
        city: 'Beijing',
        latitude: 39.916667, 
        longitude: 116.383333,
    },
    {   continent: 'Asia',
        country: 'Japan',
        city: 'Tokyo',
        latitude: 35.683333, 
        longitude: 139.683333,
    },
]
